const express = require('express')
const expressJoi = require('@escook/express-joi')
const { add_cate_schema, delete_cate_schema, get_cate_schema, update_cate_schema } = require('../schema/artcate')
const router = express.Router()
const { getArticleCate, addArticleCate, deleteArticleCate, getArticleCateById, updateArticleCateById } = require('../router_handler/article')
router.get('/cates', getArticleCate)
router.post('/addcates', expressJoi(add_cate_schema), addArticleCate)
router.get('/deletecate/:id', expressJoi(delete_cate_schema), deleteArticleCate)
router.get('/cates/:id', expressJoi(get_cate_schema), getArticleCateById)
router.post('/updatecate', expressJoi(update_cate_schema), updateArticleCateById)
module.exports = router